// app/layout.tsx
import type { Metadata } from "next";
import { Geist, Geist_Mono, Bebas_Neue, Poppins, Space_Grotesk } from "next/font/google";
import "./globals.css";
import { config } from "@fortawesome/fontawesome-svg-core";
import "@fortawesome/fontawesome-svg-core/styles.css";
import Nav from "./components/Nav";
import SmoothScroller from "./components/SmoothScroller";

config.autoAddCss = false;

// Font loading
const geistSans = Geist({ variable: "--font-geist-sans", subsets: ["latin"] });
const bebasNeue = Bebas_Neue({ variable: "--font-bebas-neue", subsets: ["latin"], weight: "400" });
const poppins = Poppins({ variable: "--font-poppins", subsets: ["latin"], weight: ["400", "500", "600", "700"] });
const space = Space_Grotesk({ variable: "--font-space-grotesk", subsets: ["latin"], weight: ["400", "500", "600", "700"] });
const geistMono = Geist_Mono({ variable: "--font-geist-mono", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className="h-full">
      <body className={`${geistSans.variable} ${geistMono.variable} ${bebasNeue.variable} ${poppins.variable} ${space.variable} antialiased h-full`}>
        <SmoothScroller>
          <Nav />
          {children}
        </SmoothScroller>
      </body>
    </html>
  );
}